### ISSUE TITLE
Question regarding the noise in the input data

### ISSUE THREAD

**Issue by hezequn** [Andrewpensoneault/HMC-B-PINN---Jax-tutorial#1]
Hi Andrew, 

Thanks for sharing this fantastic notebook!

I noticed that in the "Limitations of B-PINN" part, you mentioned that the boundary and residual points are assumed to be noise-free. This assumption is also implemented in your code when generating `bd_data` and `f_data`. In the B-PINNs paper, Eqt. 3, I think they assume that the independent Gaussian noise with zero mean is added to all the data (u, f, b) and in the likelihood (Eqt. 5), these noisy data are used to calculate the differences. Maybe I am missing something here. Any comments will be appreciated. Thanks.

Zequn

**Comment by Andrewpensoneault** [comment]
Hi Zequn,
Thank you for contacting me. For this setup, I assume the right hand side function f(x) and the boundary function b(x) are known exactly. Thus, you can draw as many noise-free residual points as you would like by evaluating f(x). Additionally, we assume the boundary conditions are known exactly, thus there is no noise the boundary either.

The Gaussian likelihood assumption with nonzero small standard deviation on the residual and boundary is made to allow us to apply the HMC we need to be able to construct a posterior density for the algorithm. Additionally, this assumption acts as a sort of soft constraint on the physics and boundary information. This is similar to the assumption made in this paper in equation (8):

https://www.sciencedirect.com/science/article/pii/S2095034920300295

I will add some more details to the tutorial to clarify this, thank you for contacting me.

Andrew

**Comment by hezequn** [comment]
> 
Hi Andrew,

Thanks a lot for the prompt and detailed response! I will read the paper you shared to have a better understanding. Thanks.

Best,
Zequn
